### ISSUE TITLE
.storybook folder is missing

### ISSUE THREAD

**Issue by Tusko** [xiscohv/primevue-ts-storybook#1]
![CleanShot 2023-12-07 at 15 48 49@2x](https://github.com/xiscohv/primevue-ts-storybook/assets/2039259/4c54df08-f3bb-4af4-a7c9-a2481c69252c)

**Comment by xiscohv** [comment]
This should be fixed with my last commit! Can you confirm?

**Comment by Tusko** [comment]
Tha's it!

thanks)
